//Generated by GuiGenie - Copyright (c) 2004 Mario Awad.
//Home Page http://guigenie.cjb.net - Check often for new versions!

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.event.*;

public class MyPanel extends JPanel {
  private JButton botonEnviarDatos;
  private JLabel etiquetaPeso;
  private JLabel etiquetaAltura;
  private JLabel etiquetaEdad;
  private JLabel etiquetaGenero ;
  private JTextField campoTextoPeso;
  private JTextField campoTextoAltura;
  private JTextField campoTextoEdad;
  private JTextField campoTextoGenero;
  private JLabel etiquetaTitulo;
  private JLabel etiquetaRutinas;
  private JLabel etiquetaRecetas;
  private JLabel nombreApp;

  public MyPanel() {
    //construct components
    botonEnviarDatos = new JButton ("ENVIAR");
    etiquetaPeso = new JLabel ("Peso: ");
    etiquetaAltura = new JLabel ("Altura: ");
    etiquetaEdad = new JLabel ("Edad: ");
    etiquetaGenero  = new JLabel ("Genero: ");
    campoTextoPeso = new JTextField (5);
    campoTextoAltura = new JTextField (5);
    campoTextoEdad = new JTextField (5);
    campoTextoGenero = new JTextField (5);
    etiquetaTitulo = new JLabel ("Tus datos");
    etiquetaRutinas = new JLabel ("...");
    etiquetaRecetas = new JLabel ("...");
    nombreApp = new JLabel ("Fat2Fit");

    //adjust size and set layout
    setPreferredSize (new Dimension (1176, 809));
    setLayout (null);

    //add components
    add (botonEnviarDatos);
    add (etiquetaPeso);
    add (etiquetaAltura);
    add (etiquetaEdad);
    add (etiquetaGenero );
    add (campoTextoPeso);
    add (campoTextoAltura);
    add (campoTextoEdad);
    add (campoTextoGenero);
    add (etiquetaTitulo);
    add (etiquetaRutinas);
    add (etiquetaRecetas);
    add (nombreApp);

    //set component bounds (only needed by Absolute Positioning)
    botonEnviarDatos.setBounds (70, 325, 100, 20);
    etiquetaPeso.setBounds (45, 130, 100, 25);
    etiquetaAltura.setBounds (45, 175, 100, 25);
    etiquetaEdad.setBounds (40, 220, 100, 25);
    etiquetaGenero .setBounds (40, 265, 100, 25);
    campoTextoPeso.setBounds (115, 135, 100, 25);
    campoTextoAltura.setBounds (115, 180, 100, 25);
    campoTextoEdad.setBounds (115, 220, 100, 25);
    campoTextoGenero.setBounds (115, 265, 100, 25);
    etiquetaTitulo.setBounds (85, 90, 70, 25);
    etiquetaRutinas.setBounds (405, 110, 100, 25);
    etiquetaRecetas.setBounds (405, 235, 100, 25);
    nombreApp.setBounds (10, 10, 100, 25);
    }


  public static void main (String[] args) {
    JFrame frame = new JFrame ("MyPanel");
    frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
    frame.getContentPane().add (new MyPanel());
    frame.pack();
    frame.setVisible (true);
  }
}
